# call my labels
u_um <- function(Text) bquote(.(Text) ~ "[" * mu * "m]")
u_cm2 <- function(Text) bquote(.(Text) ~ "[" * cm^2 * "]")
u_g_m2 <- function(Text) bquote(.(Text) ~ "[g " * m^-2 * "]")
u_mol_mol <- function(Text) bquote(.(Text) ~ "[mol " * mol^-1 * "]")
u_umol_mol <- function(Text) bquote(.(Text) ~ "[" * mu * "mol" ~ mol^-1 * "]")
u_mmol_m2 <- function(Text) bquote(.(Text) ~ "[mmol" ~ m^-2, "]")
u_PFD <- function(Text) bquote(.(Text) ~ "[" * mu * "mol" ~ m^-2 ~ s^-1 * "]")
u_SPFD <- function(Text) bquote(.(Text) ~ "[" * mu * "mol" ~ m^-2 ~ s^-1 ~ nm^-1 * "]")

u_Pn <- expression(paste(italic(P)[n] ~ "[" * mu * "mol" * CO[2] ~ m^-2 ~ s^-1 * "]"))
u_deltaPn <- expression(paste(Delta * italic(P)[n] ~ "[" * mu * "mol" * CO[2] ~ m^-2 ~ s^-1 * "]"))
u_Pg <- expression(paste(italic(P)[g] ~ "[" * mu * "mol" * CO[2] ~ m^-2 ~ s^-1 * "]"))
u_Gs <- expression(paste(italic(g)[s] ~ "[mol" * H[2] * "O" ~ m^-2 ~ s^-1 * "]"))
u_Ci <- expression(paste(italic(C)[i] ~ "[Pa]"))
u_Ca <- expression(paste(italic(C)[a] ~ "[Pa]"))