mean2 <- function(x) mean(x, na.rm = T)
sd2 <- function(x) sd(x, na.rm = TRUE)
se <- function(x) sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))
length2 <- function(x) sum(!is.na(x))

library(shiny)
library(plyr)
library(dplyr)
library(ggplot2)
library(data.table)
library(stringr)
library(magrittr)
library(tidyr)
library(reshape2)
library(RCurl)
library(agricolae)
library(rCharts)
library(googleVis)